name: bierzaehler
description: Optimal um seinen Bierkonsum zu kontrollieren.

version: 7.0.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^3.1.0
  # Bloc for state management
  flutter_bloc: ^3.2.0
  # Value equality
  equatable: ^1.0.3
  # Functional programming thingies
  dartz: ^0.8.9
  # Remote API
  connectivity: ^0.4.6+2
  http: ^0.12.0+4
  # Local cache
  shared_preferences: ^0.5.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  uses-material-design: true

  fonts:
  - family:  MyFlutterApp
    fonts:
    - asset: fonts/MyFlutterApp.ttf