name: bierzaehler
description: Optimal um seinen Bierkonsum zu kontrollieren.

version: 7.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Provider for state management
  provider: ^4.3.2+2
  # Value equality
  equatable: ^1.2.5
  # Database access
  sqflite: ^1.3.1+1
  freezed_annotation: ^0.12.0
  injectable: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.2

  freezed:
  injectable_generator:
  build_runner:

flutter:
  uses-material-design: true

  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf